### ISSUE TITLE
Question Angular 2

### ISSUE THREAD

**Issue by geneeblack** [angular-dashboard-framework/angular-dashboard-framework#270] opened 2016-09-10 22:17 UTC
Any plans to port this to Angular 2? It's a great reference project but I'm just learning Angular 2 and am not ready to attempt to port this myself. It would be a great resource though.

**Comment by raulgomis** [comment] 2016-09-17 09:53
Hi @geneeblack, this question was already raised some time ago: #214. Let's use the other thread to discuss about the migration to Angular 2.

**Comment by raulgomis** [comment] 2016-09-20 10:21
@geneeblack could you close this issue, please?

**Comment by sdorra** [comment] 2016-09-27 13:58
Duplicate of #214

**Closed by sdorra** 2016-09-27 13:58 UTC
Labels: duplicate
