### ISSUE TITLE
Error in changing widget title

### ISSUE THREAD

**Issue by chule143** [angular-dashboard-framework/angular-dashboard-framework#229] opened 2016-03-30 20:25 UTC
When I tried to change the name of the widget from the modal, I receive this message:

```console
TypeError: Cannot read property 'apply' of undefined
    at Scope.editScope.saveDialog 
```
referenced from:
```javascript
// build injection locals
            var widget = $scope.widget;
            var applyFn = widget.edit.apply;
            var locals = {
              widget: widget,
              definition: editScope.definition,
              config: editScope.definition.config
            };
```

**Comment by sdorra** [comment] 2016-04-29 09:46
Duplicate of #211

**Closed by sdorra** 2016-04-29 09:46 UTC
Labels: duplicate
