### ISSUE TITLE
Add support to i18n

### ISSUE THREAD

**Issue by duilio82** [angular-dashboard-framework/angular-dashboard-framework#240] opened 2016-04-21 15:15 UTC
It would be great to add i18n.

For example change "Are you sure..." in https://github.com/angular-dashboard-framework/angular-dashboard-framework/blob/master/src/templates/widget-delete.html

**Comment by sdorra** [comment] 2016-04-29 09:22
Duplicate of #102

**Closed by sdorra** 2016-04-29 09:22 UTC
Labels: duplicate
